### ISSUE TITLE
Keep multiline value

### ISSUE THREAD

**Issue by eggplants** [xbcsmith/ymlfxr#9]
I would like to keep multiline value like this:

```yaml
foo:
  - bar: |
      echo 1
      echo 2
```

But now ymlfxr fixes into:

```yaml
foo:
  - bar: "echo 1\necho 2\n"
```
